# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "L'intelligence artificielle générative à l’ULB"
author: <a href="https://www.ulb.be/fr/intelligence-artificielle/academ%C2%B7ia-plan-de-formation-pour-lintelligence-artificielle">Université libre de Bruxelles - Academ·IA</a> 
copyright: ""
logo: ulb_academia.png 

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"
  exclude_patterns          : ['helper_functions','Chapter_*','Not_to_be_published']

# Information about where the book exists on the web
repository:
  url: https://github.com/ULB-AcademIA/guide_usages_IA # Online location of your book
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# Advanced and power-user settings


html:
  favicon                   : "IA.png"  # A path to a favicon image
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar : true
  #navbar_number_sections: false
  theme: "sphinx_book_theme"
  extra_footer: |
    <p>
    Copyright ULB, 2025 <!--Licence: <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr">CC BY-SA 4.0</a>-->
    </p>

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image

#sphinx:
#   config:    
#         html_theme_options:
#          logo:
#            text: "ChatGPT, Copilot et autres assistants IA : Guide des usages à l’ULB"    

